language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7

install:
  - go get -v -t ./...
  - go get -u godoc.org/golang.org/x/tools/cmd/cover

script:
  - go build
  - go test -v -covermode=count -coverprofile=profile.cov ./...

after_success:
  - go get -u github.com/mattn/goveralls
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
